### ISSUE TITLE
Feedback on Milestone #1

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/mini_tidy_python#12]
Great job team! Your packages are well organized and your functions are tests are clearly defined. Nice job implementing `roxygen`, way to go above and beyond! A few comments:

- I'm not sure why you have two files for a license.
- It would be good if you could include error messages on your tests. This will make your testing more user friendly. Also defining your tests as "Test 1", "Test 2", ... etc. isn't the most useful practice. It might be better to define your test as something more practical.
- As far as I can tell, all of your tests are on the input to your functions. You should also include tests on the output of your function, for example making sure that the output is in the desired form (data frame) and the output does not equal the input.
- You should try to test some extreme cases, e.g. all values are n/a.

**Comment by lyiris22** [comment]
Thank you for the feedback! We are making the following improvements:

- Two files for license: this seems to be for R repo and Python does not have this issue.
- Error messages already included in the tests for Python.
- For Python tests, we check if the output dataframe is equal to the expected dataframe, so the type of output is checked.
- Extreme case with all values NA are added to both `my_gather` and `my_spread` tests.
