### ISSUE TITLE
Milestone 2 Task Trackers

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/mini_tidy_python#13]
FOR PYTHON PACKAGE:

- Write code of all 3 functions and make sure they pass the test cases we wrote.

- Tasks for each of the 3 functions would be tracked in the issues below (all assigned to Milestone 2):
    - [`my_dropna`](https://github.com/UBC-MDS/mini_tidy_python/issues/14)
    - [`my_gather` ](https://github.com/UBC-MDS/mini_tidy_python/issues/17)
    - [`my_spread` ](https://github.com/UBC-MDS/mini_tidy_python/issues/18)

- Code review of all 3 functions:
    - [`my_dropna` by Iris](https://github.com/UBC-MDS/mini_tidy_python/pull/15#pullrequestreview-203528033)
    -  [`my_gather` by Orphelia](https://github.com/UBC-MDS/mini_tidy_python/pull/16#pullrequestreview-203539798)
    -  [`my_spread` by Juno](https://github.com/UBC-MDS/mini_tidy_python/pull/16#discussion_r257109531)
   
- Check if package works by user downloading and installing them from Github and use them in their own software development.

- Update documentation for below if needed:
    - Python package README (including usage and installation instructions)
    - functions
    - tests

**Comment by huijuechen** [comment]
Feb 15

After coding and reviewing the functions, we:
- tried downloading and installing the package from Github and use them in our own software development, the package worked.
- Updated documentation for below:
  * Repo structure
  * Python package README (including usage and installation instructions)
  * functions
  * tests

**Comment by lyiris22** [comment]
Feb 16
- Updated minor changes in `my_spread`
- Updated setup.py to get the package installed
